sudo: false
language: scala

matrix:
  include:
  - jdk: openjdk8
    scala: 2.12.10
  - jdk: openjdk8
    scala: 2.13.1
  - jdk: openjdk11
    scala: 2.13.1

script:
- sbt ++$TRAVIS_SCALA_VERSION test

cache:
  directories:
  - "$HOME/.cache"
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot"
