sudo: false
language: scala

matrix:
  include:
  - jdk: oraclejdk8
    scala: 2.12.6
  - jdk: oraclejdk8
    scala: 2.11.12
  - jdk: oraclejdk10
    scala: 2.12.6

script:
- sbt ++$TRAVIS_SCALA_VERSION test
